[workspace]
members = [
    "crates/toybox_c1200",

    "crates/wavekit",
    "crates/instrument",
    "crates/xtask",
    "crates/fx",
]
resolver = "2"

[workspace.dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
nih_plug_webview = { git = "https://github.com/zmann-org/nih-plug-wry.git" }
include_dir = "0.7.3"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0"

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
