[workspace]
members = [
    "crates/toybox_c1200",
    "crates/wavekit",
    "crates/instrument",
    "crates/xtask",
    "crates/fx",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
license = "GPL-3.0-or-later"

[workspace.dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
nih_plug_webview = { git = "https://github.com/AZProductions/nih-plug-webview.git" }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0"
rust-embed = { version = "8.2.0", features = ["interpolate-folder-path"] }
strum = { version = "0.26", features = ["derive"] }

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
