[package]
name = "toybox_c1200"
version = "0.0.0"
edition = "2021"
authors = ["ZMANN <info@example.com>"]
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
nih_plug_webview = { git = "https://github.com/zmann-org/nih-plug-wry.git" }
wavekit = { path = "../wavekit" }
instrument = { path = "../instrument" }
fx = { path = "../fx" }
strum_macros = "0.25.3"
serde = { version = "1.0.190", features = ["derive"] }
include_dir = "0.7.3"
