$schema: "https://moonrepo.dev/schemas/project.json"

implicitDeps:
  - "^:build"

fileGroups:
  sources:
    - "src/**/*"
    - "Cargo.toml"

tasks:
  build:
    command: "cargo xtask bundle $project"
    inputs:
      - "@globs(sources)"
    options:
      runFromWorkspaceRoot: true
      cache: false
  check:
    command: "cargo check --workspace"
    inputs:
      - "@globs(sources)"
    options:
      runInCI: false
  format:
    command: "cargo fmt --all --check"
    inputs:
      - "@globs(sources)"
    options:
      runInCI: false
  lint:
    command: "cargo clippy --workspace"
    inputs:
      - "@globs(sources)"
    options:
      runInCI: false
  
