[package]
name = "instrument"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
zstd = "0.13.0"
bincode = "1.3.3"
serde_derive = { workspace = true }
serde = { workspace = true }
rkyv = "0.7.43"
rustc-hash = "1.1.0"
