[package]
name = "instrument"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
zstd = "0.13.0"
serde_derive = { workspace = true }
serde = { workspace = true }
rkyv = { workspace = true }
rustc-hash = "1.1.0"
