name: build launcher engine [ubuntu-latest] (vacaro-launcher)
on:
  push:
    branches:
      - '*'
    paths: 
      - vacaro-launcher/**
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    defaults: 
      run: 
        working-directory: 'vacaro-launcher'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - run: npm install

      - run: npm run build
