name: Build All VSTs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal --target stable-x86_64-pc-windows-msvc --no-self-update
      - uses: ./
      - name: Build xtask
        run: cargo build -p xtask --verbose
      - name: Build Toybox C1200
        run: cargo xtask bundle toybox_c1200 --verbose