name: Monorepo

on:
  push:
    branches: ["main"]
    paths:
      - "crates/**"
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths:
      - "crates/**"
      - ".github/workflows/**"

jobs:
  package:
    strategy:
      matrix:
        include:
          - { name: windows, os: windows-latest, cross-target: "" }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Fetch all git history
        run: git fetch --force --prune --tags --unshallow
      - uses: 'moonrepo/setup-toolchain@v0'
      - run: 'moon ci'
      - uses: moonrepo/setup-rust@v1
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ matrix.name }}-${{ matrix.cross-target }}
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: moon run toybox_c1200:build
