name: Moonrepo CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

env:
  RUSTFLAGS: -C debuginfo=0 # Do not produce debug symbols to keep memory usage down

jobs:
  package:
    strategy:
      matrix:
        include:
          - { name: windows, os: windows-latest, cross-target: "" }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Fetch all git history
        run: git fetch --force --prune --tags --unshallow
      - uses: "moonrepo/setup-toolchain@v0"
      - run: "moon ci --color"
        env:
          MOONBASE_SECRET_KEY: ${{ secrets.MOONBASE_SECRET_KEY }}
      - uses: moonrepo/run-report-action@v1
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          matrix: ${{ toJSON(matrix) }}
