name: Moonrepo CI

on:
  push:
    branches: ["main"]
    paths:
      - "crates/**"
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths:
      - "crates/**"
      - ".github/workflows/**"

jobs:
  package:
    strategy:
      matrix:
        include:
          - { name: windows, os: windows-latest, cross-target: "" }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: 'moonrepo/setup-toolchain@v0'
      - run: 'moon ci'